# Generated by Django 6.1.1 on 2026-09-23 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=100, unique=True, verbose_name='Código de Barras')),
                ('description', models.CharField(max_length=255, verbose_name='Descrição')),
                ('brand', models.CharField(blank=True, max_length=100, null=True, verbose_name='Marca')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço')),
                ('quantity', models.IntegerField(default=0, verbose_name='Quantidade')),
                ('min_quantity', models.IntegerField(default=5, verbose_name='Quantidade Mínima')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
    ]
