# Generated by Django 6.1.1 on 2026-09-23 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cust',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Custo'),
            preserve_default=False,
        ),
    ]
